version: "3.9"

services:
  api:
    build:
      context: ./app
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://autoops:autoops@mysql:3306/autoops
    depends_on:
      - mysql


  agent:
    build:
      context: ./app
      dockerfile: docker/Dockerfile.agent
    depends_on:
      - api
    environment:
      API_URL: http://api:8000/ingest/metrics

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autops
      MYSQL_USER: autops
      MYSQL_PASSWORD: autops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  grafana_data:
